apiVersion: v1
kind: Service
metadata:
  name: thunderbolt-frontend-service
spec:
  selector:
    app: thunderbolt-frontend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30004
  type: NodePort
